import type { Metadata } from "next";
import Header from "./components/Header"; // Adjust the import path if needed
import Footer from "./components/Footer"; // Adjust the import path if needed
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
